# Stage 1: Build image
FROM mcr.microsoft.com/playwright/python:v1.53.0-jammy as build-image

ARG FUNCTION_DIR="/function"
WORKDIR ${FUNCTION_DIR}

# Install system dependencies
RUN apt-get update && apt-get install -y \
    g++ make cmake unzip curl \
    libcurl4-openssl-dev \
    fonts-liberation \
    libappindicator3-1 libasound2 \
    libatk-bridge2.0-0 libatk1.0-0 libcups2 \
    libdbus-1-3 libgdk-pixbuf2.0-0 libnspr4 libnss3 \
    pciutils xdg-utils \
    && rm -rf /var/lib/apt/lists/*

# Copy and install dependencies
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --target ${FUNCTION_DIR} -r requirements.txt \
    && pip install --target ${FUNCTION_DIR} awslambdaric

# Copy application code
COPY . ${FUNCTION_DIR}

# Stage 2: Final runtime
FROM mcr.microsoft.com/playwright/python:v1.53.0-jammy

ARG FUNCTION_DIR="/function"
WORKDIR ${FUNCTION_DIR}

COPY --from=build-image ${FUNCTION_DIR} ${FUNCTION_DIR}

ENTRYPOINT [ "python", "-m", "awslambdaric" ]
CMD [ "lambda_function.lambda_handler" ]
